<a href="https://colab.research.google.com/github/haradats/pandasNotebook/blob/main/pandasNote02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# DataFrameの作成

## リストからDataFrameを作成する

In [ ]:
lst = [[1,1,1], [2,4,8], [3,9,27]]
for x in lst:
  print(x)

[1, 1, 1]
[2, 4, 8]
[3, 9, 27]


In [ ]:
df = pd.DataFrame(lst, columns=['linear','square','cubic'],index=['d1','d2','d3'])
df

linear  square  cubic
d1       1       1      1
d2       2       4      8
d3       3       9     27

In [ ]:
df = pd.DataFrame(lst, columns=['linear','square','cubic'])
df

linear  square  cubic
0       1       1      1
1       2       4      8
2       3       9     27

In [ ]:
df = pd.DataFrame(lst)
df

0  1   2
0  1  1   1
1  2  4   8
2  3  9  27

## NumPyの配列からDataFrameを作成する

In [ ]:
import numpy as np
ar = np.array(lst)
ar

array([[ 1,  1,  1],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
df = pd.DataFrame(ar, columns=['linear', 'square', 'cubic'])
df

linear  square  cubic
0       1       1      1
1       2       4      8
2       3       9     27

In [ ]:
type(df)

pandas.core.frame.DataFrame

## 辞書からDataFrameを作成する

In [ ]:
dc = {'linear':[1,2,3], 'square':[1,4,9], 'cubic':[1,8,27]}
dc

{'linear': [1, 2, 3], 'square': [1, 4, 9], 'cubic': [1, 8, 27]}

In [ ]:
type(dc)

dict

In [ ]:
print(dc)

{'linear': [1, 2, 3], 'square': [1, 4, 9], 'cubic': [1, 8, 27]}


In [ ]:
df = pd.DataFrame(dc)
df

linear  square  cubic
0       1       1      1
1       2       4      8
2       3       9     27

# DataFrameの要素へのアクセス

In [ ]:
df2 = pd.DataFrame()    # 空のDataFrame
df2

Empty DataFrame
Columns: []
Index: []

## atによる要素へのアクセス

In [ ]:
df2.at['d1','linear'] = 1
df2

linear
d1     1.0

In [ ]:
df2.at['d2','square'] = 4
df2

linear  square
d1     1.0     NaN
d2     NaN     4.0

In [ ]:
df2.at['d3','cubic'] = 27
df2

linear  square  cubic
d1     1.0     NaN    NaN
d2     NaN     4.0    NaN
d3     NaN     NaN   27.0

In [ ]:
### 実習: NaNの箇所にデータを埋める

In [ ]:
df2.at['d1','square'] = 1
df2

linear  square  cubic
d1     1.0     1.0    NaN
d2     NaN     4.0    NaN
d3     NaN     NaN   27.0

In [ ]:
df2.at['d1', 'cubic']=1
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     NaN     4.0    NaN
d3     NaN     NaN   27.0

In [ ]:
df2.at['d2','linear'] = 2
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    NaN
d3     NaN     NaN   27.0

In [ ]:
df2.at['d2','cubic'] = 8
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     NaN     NaN   27.0

In [ ]:
df2.at['d3','linear'] = 3
df2
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     NaN   27.0

In [ ]:
df2.at['d3','square'] = 9
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0

## NaNを一括して別の値に置き換える方法

In [ ]:
df3 = pd.DataFrame()
df3.at['d1','linear'] = 1
df3.at['d2','square'] = 4
df3.at['d3','cubic' ] = 27
df3

linear  square  cubic
d1     1.0     NaN    NaN
d2     NaN     4.0    NaN
d3     NaN     NaN   27.0

In [ ]:
df31 = df3.fillna(0)
df31

linear  square  cubic
d1     1.0     0.0    0.0
d2     0.0     4.0    0.0
d3     0.0     0.0   27.0

In [ ]:
df3

linear  square  cubic
d1     1.0     NaN    NaN
d2     NaN     4.0    NaN
d3     NaN     NaN   27.0

## iatによる要素へのアクセス

In [ ]:
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0

In [ ]:
df2.iat[2,1]

9.0

### iatは既存の領域にのみアクセス可能

In [ ]:
# df2.iat[3,1]

## locによるアクセス

In [ ]:
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0

In [ ]:
df2.loc['d1':'d2','linear':'square']

linear  square
d1     1.0     1.0
d2     2.0     4.0

In [ ]:
df2.loc['d1':'d2',:]

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0

In [ ]:
df2.loc[:,'linear':'square']

linear  square
d1     1.0     1.0
d2     2.0     4.0
d3     3.0     9.0

In [ ]:
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0

In [ ]:
df2.loc[['d1','d3'],['linear','cubic']]

linear  cubic
d1     1.0    1.0
d3     3.0   27.0

## ilocによるアクセス

In [ ]:
df2.iloc[0:2, 0:2]

linear  square
d1     1.0     1.0
d2     2.0     4.0

In [ ]:
df2.iloc[[0, 2], [0, 2]]

linear  cubic
d1     1.0    1.0
d3     3.0   27.0

# 特定の列（カラム）にアクセスする方法

## スライスを指定する方法

In [ ]:
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0

In [ ]:
df2[['linear','cubic']]

linear  cubic
d1     1.0    1.0
d2     2.0    8.0
d3     3.0   27.0

In [ ]:
type(df2['linear'])

pandas.core.series.Series

In [ ]:
c = pd.Series(['Taro', 'Jiro', 'Hanako'], index=['d1', 'd2', 'd3'])
c

d1      Taro
d2      Jiro
d3    Hanako
dtype: object

In [ ]:
df2['name'] = c

In [ ]:
df2

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako

### 複数のカラムを取り出す方法

In [ ]:
df2[['linear', 'cubic']]

linear  cubic
d1     1.0    1.0
d2     2.0    8.0
d3     3.0   27.0

### 数値のカラム名も使用可能

In [ ]:
df3 = pd.DataFrame([[1,2],[3,4]])
df3

0  1
0  1  2
1  3  4

In [ ]:
df3[0]

0    1
1    3
Name: 0, dtype: int64

## ドットを用いる方法

In [ ]:
df4 = pd.DataFrame([['中村','大阪府',55],['田中','東京都',33]], columns=['name','address', 'age'])
df4

name address  age
0   中村     大阪府   55
1   田中     東京都   33

In [ ]:
df4.name

0    中村
1    田中
Name: name, dtype: object

### 新規カラムの追加はできない！

In [ ]:
df4.gender = ['男', '女']

<ipython-input-102-7ee78bd12629>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df4.gender = ['男', '女']


In [ ]:
df4['gender'] = ['男', '女']
df4

name address  age gender
0   中村     大阪府   55      男
1   田中     東京都   33      女

# 行の取り出し

In [ ]:
df2

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako

In [ ]:
df2.loc['d2']

linear     2.0
square     4.0
cubic      8.0
name      Jiro
Name: d2, dtype: object

In [ ]:
df2.iloc[1]

linear     2.0
square     4.0
cubic      8.0
name      Jiro
Name: d2, dtype: object

### 結論）Seriesの形で得られ、元のDataFrameのカラムがインデックスとなる。

# 行の追加

In [ ]:
df2

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako

In [ ]:
lin = pd.Series([4, 16, 64, 'Junko'], index=['linear', 'square', 'cubic', 'name'])
lin

linear        4
square       16
cubic        64
name      Junko
dtype: object

In [ ]:
type(lin)

pandas.core.series.Series

In [ ]:
df2.loc['d4'] = lin
df2

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako
d4     4.0    16.0   64.0   Junko


# DataFrameの内容をNumPyの配列に変換する方法

In [ ]:
df2.values # 旧pandasでの方法

array([[1.0, 1.0, 1.0, 'Taro'],
       [2.0, 4.0, 8.0, 'Jiro'],
       [3.0, 9.0, 27.0, 'Hanako'],
       [4.0, 16.0, 64.0, 'Junko']], dtype=object)

In [ ]:
df2.to_numpy() # 新しいpandasでの方法（推奨）

array([[1.0, 1.0, 1.0, 'Taro'],
       [2.0, 4.0, 8.0, 'Jiro'],
       [3.0, 9.0, 27.0, 'Hanako'],
       [4.0, 16.0, 64.0, 'Junko']], dtype=object)

# インデックス、カラムを明に取り出す方法

In [ ]:
df2.index

Index(['d1', 'd2', 'd3', 'd4'], dtype='object')

In [ ]:
df2.columns

Index(['linear', 'square', 'cubic', 'name'], dtype='object')

In [ ]:
df2.index.to_numpy()

array(['d1', 'd2', 'd3', 'd4'], dtype=object)

In [ ]:
type(df2.index)

pandas.core.indexes.base.Index

In [ ]:
df2.columns.to_numpy()

array(['linear', 'square', 'cubic', 'name'], dtype=object)

## 指定したインデックス、カラムの位置を調べる方法

In [ ]:
df2

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako
d4     4.0    16.0   64.0   Junko

In [ ]:
df2.index.get_loc('d3')

2

In [ ]:
df2.columns.get_loc('square')

1

# 整列（ソート）

## 値に沿った整列

In [ ]:
df2

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako
d4     4.0    16.0   64.0   Junko

In [ ]:
df21 = df2.sort_values(by='name')

In [ ]:
df21

linear  square  cubic    name
d3     3.0     9.0   27.0  Hanako
d2     2.0     4.0    8.0    Jiro
d4     4.0    16.0   64.0   Junko
d1     1.0     1.0    1.0    Taro

In [ ]:
df22 = df2.sort_values(by='name', ascending=False)
df22

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d4     4.0    16.0   64.0   Junko
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako

In [ ]:
df21

linear  square  cubic    name
d3     3.0     9.0   27.0  Hanako
d2     2.0     4.0    8.0    Jiro
d4     4.0    16.0   64.0   Junko
d1     1.0     1.0    1.0    Taro

In [ ]:
df21.sort_index()

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako
d4     4.0    16.0   64.0   Junko

# 行、列の削除

In [ ]:
df2

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako
d4     4.0    16.0   64.0   Junko

In [ ]:
df22 = df2.drop('d4')
df22

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako

In [ ]:
df22 = df2.drop(columns='name')
df22

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0
d4     4.0    16.0   64.0

In [ ]:
df2

linear  square  cubic    name
d1     1.0     1.0    1.0    Taro
d2     2.0     4.0    8.0    Jiro
d3     3.0     9.0   27.0  Hanako
d4     4.0    16.0   64.0   Junko

In [ ]:
df2.drop(index='d4', columns='cubic')

linear  square    name
d1     1.0     1.0    Taro
d2     2.0     4.0    Jiro
d3     3.0     9.0  Hanako

In [ ]:
df22 = df2.drop(index=['d1','d4'], columns=['linear','cubic'])
df22

square    name
d2     4.0    Jiro
d3     9.0  Hanako

## カラムの抹消

In [ ]:
del df2['name']

In [ ]:
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0
d4     4.0    16.0   64.0

# DataFrameの連結

## 行方向に単純に連結する

In [ ]:
dfA = pd.DataFrame([['1a', '1b'], ['2a', '2b']], index=['d1', 'd2'], columns=['a', 'b'])

In [ ]:
dfA

a   b
d1  1a  1b
d2  2a  2b

In [ ]:
dfA = pd.DataFrame([['1a', '1b'], ['2a', '2b']], index=['d1', 'd2'], columns=['a', 'b'])
dfB = pd.DataFrame([['3a', '3b'], ['4a', '4b']], index=['d3', 'd4'], columns=['a', 'b'])

In [ ]:
dfB

a   b
d3  3a  3b
d4  4a  4b

In [ ]:
display(dfA);display(dfB)

a   b
d1  1a  1b
d2  2a  2b

a   b
d3  3a  3b
d4  4a  4b

In [ ]:
dfAB = pd.concat([dfA, dfB])
dfAB

a   b
d1  1a  1b
d2  2a  2b
d3  3a  3b
d4  4a  4b

In [ ]:
dfBA = pd.concat([dfB, dfA])
dfBA

a   b
d3  3a  3b
d4  4a  4b
d1  1a  1b
d2  2a  2b

### 共通しないカラムがある場合

In [ ]:
dfC = pd.DataFrame([['3c', '3d'], ['4c', '4d']], index=['d3', 'd4'], columns=['c', 'd'])
dfC

c   d
d3  3c  3d
d4  4c  4d

In [ ]:
dfAC = pd.concat([dfA, dfC])
dfAC

a    b    c    d
d1   1a   1b  NaN  NaN
d2   2a   2b  NaN  NaN
d3  NaN  NaN   3c   3d
d4  NaN  NaN   4c   4d

## 横方向（カラム方向）の連結

In [ ]:
dfD = pd.DataFrame([['1e', '1f'], ['2e', '2f'], ['3e', '3f']], index=['d1', 'd2', 'd3'], columns=['e', 'f'])
dfD

e   f
d1  1e  1f
d2  2e  2f
d3  3e  3f

In [ ]:
dfAD = pd.concat([dfA, dfD], axis=1)
dfAD

a    b   e   f
d1   1a   1b  1e  1f
d2   2a   2b  2e  2f
d3  NaN  NaN  3e  3f

In [ ]:
dfA

a   b
d1  1a  1b
d2  2a  2b

### 結論）共通するインデックスが対応する

# 条件指定によるデータの抽出

In [ ]:
df3 = pd.DataFrame([
    ['taro', 'male', 35],
    ['hanako', 'female', 31],
    ['jiro', 'male', 23],
    ['junko', 'female', 21]
], columns=['name', 'gender', 'age'])

In [ ]:
df3

name  gender  age
0    taro    male   35
1  hanako  female   31
2    jiro    male   23
3   junko  female   21

## マスクの用意

In [ ]:
cond = [False, True, False, False]
cond

[False, True, False, False]

## スライスに真理値のマスクを与える

In [ ]:
df31 = df3[cond]
df31

name  gender  age
1  hanako  female   31

In [ ]:
df3

name  gender  age
0    taro    male   35
1  hanako  female   31
2    jiro    male   23
3   junko  female   21

In [ ]:
df3[ df3['gender']=='female' ]

name  gender  age
1  hanako  female   31
3   junko  female   21

In [ ]:
df3['gender'] == 'female'

0    False
1     True
2    False
3     True
Name: gender, dtype: bool

## 複雑な条件式の使用

In [ ]:
df3[(df3['gender']=='female') & (df3['age']<30)]   # 「かつ」で条件を連結

name  gender  age
3  junko  female   21

In [ ]:
df3[(df3['gender']=='male')]

name gender  age
0  taro   male   35
2  jiro   male   23

In [ ]:
df3[~(df3['gender']=='male')]   # 否定文

name  gender  age
1  hanako  female   31
3   junko  female   21

# DataFrameに関する情報の取得

## 要約統計量

In [ ]:
df2

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0
d4     4.0    16.0   64.0

In [ ]:
df2.describe()

linear     square      cubic
count  4.000000   4.000000   4.000000
mean   2.500000   7.500000  25.000000
std    1.290994   6.557439  28.225284
min    1.000000   1.000000   1.000000
25%    1.750000   3.250000   6.250000
50%    2.500000   6.500000  17.500000
75%    3.250000  10.750000  36.250000
max    4.000000  16.000000  64.000000

## データ構造に関する情報の取得

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, d1 to d4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   linear  4 non-null      float64
 1   square  4 non-null      float64
 2   cubic   4 non-null      float64
dtypes: float64(3)
memory usage: 300.0+ bytes


# 開始部分、終了部分の取り出し

In [ ]:
df2.head()

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0
d4     4.0    16.0   64.0

In [ ]:
df2.tail()

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0
d4     4.0    16.0   64.0

In [ ]:
df2.head(2)

linear  square  cubic
d1     1.0     1.0    1.0
d2     2.0     4.0    8.0

In [ ]:
df2.tail(3)

linear  square  cubic
d2     2.0     4.0    8.0
d3     3.0     9.0   27.0
d4     4.0    16.0   64.0